import type { MenuDataModel } from "./menu/menuItem.model";

export const menuData: MenuDataModel = {
	mainHeaderText: "Manufacturing",
	subHeaderText: "System Menu",
	menuItems: [
		{
			id: "partners",
			text: "Partners",
			icon: "user-friends",
			iconColor: "text-indigo-400",
			isFolder: true,
			items: [
				{
					id: "suppliers",
					text: "Suppliers",
					icon: "truck-loading",
					iconColor: "text-amber-400",
					isFolder: false,
					items: [],
				},
				{
					id: "customers",
					text: "Customers",
					icon: "user-tag",
					iconColor: "text-teal-400",
					isFolder: false,
					items: [],
				},
			],
		},
		{
			id: "products",
			text: "Products",
			icon: "box",
			iconColor: "text-orange-400",
			isFolder: true,
			items: [
				{
					id: "raw-materials",
					text: "Raw Materials",
					icon: "boxes",
					iconColor: "text-stone-400",
					isFolder: false,
					items: [],
				},
				{
					id: "special-products",
					text: "Special Products",
					icon: "star",
					iconColor: "text-fuchsia-400",
					isFolder: false,
					items: [],
				},
			],
		},
		{
			id: "documents",
			text: "Documents",
			icon: "file-invoice",
			iconColor: "text-amber-400",
			isFolder: true,
			items: [
				{
					id: "purchase-documents",
					text: "Purchase",
					icon: "shopping-cart",
					iconColor: "text-green-400",
					isFolder: false,
					items: [],
				},
				{
					id: "sale-documents",
					text: "Sale",
					icon: "cash-register",
					iconColor: "text-blue-400",
					isFolder: false,
					items: [],
				},
				{
					id: "production-documents",
					text: "Production",
					icon: "industry",
					iconColor: "text-purple-400",
					isFolder: false,
					items: [],
				},
				{
					id: "adjustment-documents",
					text: "Adjustment",
					icon: "sliders-h",
					iconColor: "text-rose-400",
					isFolder: false,
					items: [],
				},
			],
		},
		{
			id: "laboratory",
			text: "Laboratory",
			icon: "flask",
			iconColor: "text-cyan-400",
			isFolder: true,
			items: [
				{
					id: "recipes",
					text: "Recipes",
					icon: "book-open",
					iconColor: "text-lime-400",
					isFolder: false,
					items: [],
				},
			],
		},
		{
			id: "reports",
			text: "Reports",
			icon: "chart-bar",
			iconColor: "text-emerald-400",
			isFolder: true,
			items: [
				{
					id: "lot-balance",
					text: "Lot Balance",
					icon: "balance-scale",
					iconColor: "text-yellow-400",
					isFolder: false,
					items: [],
				},
			],
		},
	],
};
